# Standardpakete und Einstellungen f√ºr die Basisrolle
base_packages:
  - htop
  - git
  - curl
  - vim
  - nano
  - net-tools
timezone: "Europe/Berlin"

wifi_enabled: false
wifi_ssid: ""
wifi_password: ""
wifi_interface: "wlan0"
