---
xibo_base_path: /opt/xibo-docker

xibo_env_file: config.env

xibo_db_image: mysql:8.4
xibo_db_root_password: rootpass
xibo_db_container: xibo-db
xibo_db_name: xibo
xibo_db_user: xibo
xibo_db_password: xibopass
xibo_db_mem: 1g

xibo_cms_image: ghcr.io/xibosignage/xibo-cms:release-4.4.0
xibo_cms_container: xibo-cms
xibo_cms_port_host: 8080
xibo_cms_mem: 1g

xibo_xmr_image: ghcr.io/xibosignage/xibo-xmr:1.0
xibo_xmr_container: xibo-xmr
xibo_xmr_port: 9505
xibo_xmr_mem: 256m

xibo_memcached_container: xibo-memcached
xibo_memcached_mem: 128m
xibo_memcached_size: 64

xibo_loginname_default: xibo_admin
xibo_loginpassword_default: password
