# Xibo Admin Defaults
xibo_admin_old: "admin"
xibo_admin_new: "xibo"

# DB Defaults (optional, aber sinnvoll)
xibo_db_name: xibo
xibo_db_user: xibo
xibo_db_password: xibopass
xibo_db_container: xibo-db
