- name: Add xibo user to docker group
  become: yes
  ansible.builtin.user:
    name: xibo
    groups: docker
    append: yes

- name: FÃ¼ge User xibo zur www-data Gruppe hinzu
  become: yes
  user:
    name: xibo
    groups: www-data
    append: yes
